name: USGOVRAG

on:
  pull_request:
    types:
      - synchronize
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  sqlmesh_bot:
    name: SQLMesh Bot Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Required to access code in PR
      issues: write         # Required to post comments
      checks: write         # Required to update check runs
      pull-requests: write  # Required to merge
    env:
      ENVIRONMENT: prod
      GATEWAY: default
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash

      - name: Run CI/CD Bot
        run: |
          sqlmesh_cicd -p ${{ github.workspace }} github --token ${{ secrets.GITHUB_TOKEN }} run-all